### ISSUE TITLE
Allow for file merge.

### ISSUE THREAD

**Issue by sebastian-zarzycki** [angular-translate/bower-angular-translate-loader-static-files#14]
I've used lodash _.merge, but you obviously might want to replace with own function. What this does, is that it allows translations files to merge into one single object, as opposed to overwrite (as it is now).

Additionally, I've fixed couple small mistakes (currently not relevant, but bugs, nevertheless - you pass file, so use file). 

```
@@ -42,7 +42,7 @@
                 $http(angular.extend({
                     url: [
                         file.prefix,
-                        options.key,
+                        file.key,
                         file.suffix
                     ].join(''),
                     method: 'GET',
@@ -50,7 +50,7 @@
                 }, options.$http)).success(function (data) {
                     deferred.resolve(data);
                 }).error(function (data) {
-                    deferred.reject(options.key);
+                    deferred.reject(file.key);
                 });
 
                 return deferred.promise;
@@ -74,6 +74,10 @@
 
                 for (var i = 0; i < length; i++) {
                     for (var key in data[i]) {
+			            if (!mergedData[key]) {
+			              mergedData[key] = {};
+			            }
+			            mergedData[key] = _.merge(mergedData[key], data[i][key]);
                         mergedData[key] = data[i][key];
                     }
                 }
```

**Comment by giuseppedifiore** [comment]
Hi, I have the same problem... 
for now, I've used this soution
mergedData[key] = angular.merge({},data[i][key],mergedData[key]);

**Comment by knalli** [comment]
Hi @sebastian-zarzycki  and @giuseppedifiore 

Sorry for the delay, but this repository is only atm only a shadow repository for bower. The main support (bugs, feature requests) will be found at https://github.com/angular-translate/angular-translate/issues. 

Without going into it deeper, it does look like a nice addition and contribution. Eventually it would be good for the other loader as well.

We are welcome pull requests, please have a look at https://github.com/angular-translate/angular-translate/blob/master/CONTRIBUTING.md
