### ISSUE TITLE
pluralize and advanced format doesn't work

### ISSUE THREAD

**Issue by 0xbaadf00d** [angular-translate/bower-angular-translate-loader-static-files#16]
Hi,

I have some issue with this plugin :

  - Pluralize form seem not working
  - Advanced format seem not working
  - Simple format does not respect the current local (in my case: FR) to print floating number.

###### bower.json
    "angular": "1.3.15",
    "angular-route": "1.3.x",
    "angular-loader": "1.3.x",
    "angular-mocks": "~1.3.x",
    "html5-boilerplate": "~4.3.0",
    "angular-i18n" : "v1.4.0-rc.1",
    "angular-translate" : "2.6.1",
    "angular-translate-loader-static-files" : "2.6.1",
    "angular-translate-storage-cookie" : "2.6.1",
    "angular-dynamic-locale" : "0.1.27"

###### app.js
    'use strict';

    // Declare app level module which depends on views, and components
    angular.module('myApp', [
    'ngRoute',
    'ngCookies',
    'pascalprecht.translate',
    'tmh.dynamicLocale',
    'myApp.home',
    'myApp.view2',
    'myApp.version'
    ]).
    config(['$routeProvider', function ($routeProvider) {
        $routeProvider.otherwise({redirectTo: '/home'});

    }]).
    config(["$translateProvider", function ($translateProvider) {
        $translateProvider.useStaticFilesLoader({
            prefix: 'locale-',
            suffix: '.json'
        });
        $translateProvider.preferredLanguage("en");
    }])
    .config(["tmhDynamicLocaleProvider", function (tmhDynamicLocaleProvider) {
        tmhDynamicLocaleProvider.localeLocationPattern('https://code.angularjs.org/1.2.20/i18n/angular-locale_{{locale}}.js');
    }])

###### locale-en.json
    {
        "LIKE_TEXT" : "{GENDER, select, male{He} female{She} other{They}} liked this.",
        "CAT"       : "{COUNT, plural, one {1 cat} other {# cats}}."
        "AMOUNT"    : "{{AMOUNT}} EUR",
    }

###### home.html
    <ANY translate="AMOUNT" translate-values="{ AMOUNT: 23.23 }"></ANY>
    <br/>
    {{'AMOUNT' | translate: "{AMOUNT: 45.23}"}}
    <hr>
    <ANY translate="CAT" translate-values="{ COUNT: 0 }"></ANY>
    <hr>
    <ANY translate="LIKE_TEXT" translate-values="{ GENDER: 'male' }"></ANY>

###### OUTPUT (CHROME 42)
    23.23 EUR 
    45.23 EUR
    ___________________________________________________
    {COUNT, plural, one {1 cat} other {# cats}}
    ___________________________________________________
    {GENDER, select, male{He} female{She} other{They}} liked this.

**Comment by knalli** [comment]
Hi, it looks like you are using MessageFormat and you do not have included the appropriate libraries? Please have a look at http://angular-translate.github.io/docs/#/guide/14_pluralization

**Comment by knalli** [comment]
I'm closing this again. If you are still faced with an issue, please go to the main repo's issue page https://github.com/angular-translate/angular-translate/issues

Thank you.
