### ISSUE TITLE
Unknown provider: aProvider <- a <- $http <- $translateStaticFilesLoader

### ISSUE THREAD

**Issue by keepscoding** [angular-translate/bower-angular-translate-loader-static-files#18]

**Comment by tspaeth** [comment]
Sorry, without any further description, we can't help as we're no magicians (even though we would love to be :-) ) to guess the setup you're using and where the issue is coming from.

Please file any issues in our main repo at  https://github.com/angular-translate/angular-translate/issues

**Comment by JeremyPinhel** [comment]
I have the same issue when i use custom interceptor.

**Comment by PascalPrecht** [comment]
@JeremyPinhel this error occours when you minify your code, without using string annotations for dependency injection. Make sure your DI annotations are minification safe.

**Comment by keepscoding** [comment]
possible come from $q and u may not expect this cause the error.
