### ISSUE TITLE
Error while bower installing 'bower-angular-translate-loader-static-files.git'

### ISSUE THREAD

**Issue by VaibhavP17** [angular-translate/bower-angular-translate-loader-static-files#20]
I am getting the following error while installing "bower-angular-translate-loader-static-files.git" -

bower angular-translate-loader-static-files#~2.7.2 cached git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.7.2
bower angular-translate-loader-static-files#~2.7.2 validate 2.7.2 against git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#~2.7.2
bower angular-translate-loader-static-files#~2.7.2 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git", exit code of #128 fatal: read error: Connection reset by peer

What could be the reason for the same ?

**Comment by tspaeth** [comment]
There's no need to open issues twice. And this is only the bower shadow repository. https://github.com/angular-translate/angular-translate/issues/1332 is already the correct place.
