### ISSUE TITLE
angular.js:68 Uncaught Error: [$injector:unpr] Unknown provider: $translateStaticFilesLoaderProvider <- $translateStaticFilesLoader

### ISSUE THREAD

**Issue by jitugeo** [angular-translate/bower-angular-translate-loader-static-files#21]
Hello,
I'm using angualr 1.5 and following moduler approach.
I"m trying to use the angular-translate-loader-static-files to load the files dynamically and following the documentation from here
https://angular-translate.github.io/docs/#/guide/12_asynchronous-loading.

I have installed angular-translate and it works fine, but when i install angular-translate-loader-static-files
and try to use it then throw an error.
angular.js:68 Uncaught Error: [$injector:unpr] Unknown provider: $translateStaticFilesLoaderProvider <- $translateStaticFilesLoader

I sometimes also got an error
angular-translate-loader-static-files.js:16 Uncaught ReferenceError: module is not defined

I have checked my index.html and it includes the static files. Even i can access that on browser from resource.

<!doctype html>
<html ng-app="MainApp" ng-strict-di>

<head>
  
  
  
  <meta charset="utf-8">
  <title>MyAdvisor - {{title}}</title>
  <script src="https://static.opentok.com/v2/js/opentok.js" charset="utf-8"></script>
  <meta name="description" content="{{description}}">
  <meta name="keywords" content="{{keywords}}" />
  <meta name="viewport" content="width=device-width">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  
  
  
  <link rel="stylesheet" href="../bower_components/angular-toastr/dist/angular-toastr.css" />
  <link rel="stylesheet" href="../bower_components/animate.css/animate.css" />
  <link rel="stylesheet" href="../bower_components/videogular-themes-default/videogular.css" />
  <link rel="stylesheet" href="../bower_components/c3/c3.css" />
  <link rel="stylesheet" href="../bower_components/fullcalendar/dist/fullcalendar.css" />
  <link rel="stylesheet" href="../bower_components/angular-xeditable/dist/css/xeditable.css" />
  <link rel="stylesheet" href="../bower_components/seiyria-bootstrap-slider/dist/css/bootstrap-slider.css" />
  <link rel="stylesheet" href="../bower_components/angular-carousel/dist/angular-carousel.css" />
  <link rel="stylesheet" href="../bower_components/angularjs-datepicker/dist/angular-datepicker.css" />
  
  
  
  
  <link rel="stylesheet" href="/app/shared/scss/index.css">
  
  
  <base href="/">
  <style id="antiClickjack">body{display:none !important;}</style>
  <script type="text/javascript">
    if (self === top) {
      var antiClickjack = document.getElementById("antiClickjack");
      antiClickjack.parentNode.removeChild(antiClickjack);
    } else {
      top.location = self.location;
    }
  </script>
</head>

<body>
  
  <div ui-view></div>
  
  
  <script src="../bower_components/jquery/dist/jquery.js"></script>
  <script src="../bower_components/angular/angular.js"></script>
  <script src="../bower_components/angular-animate/angular-animate.js"></script>
  <script src="../bower_components/angular-aria/angular-aria.js"></script>
  <script src="../bower_components/angular-touch/angular-touch.js"></script>
  <script src="../bower_components/lodash/lodash.js"></script>
  <script src="../bower_components/restangular/dist/restangular.js"></script>
  <script src="../bower_components/angular-ui-router/release/angular-ui-router.js"></script>
  <script src="../bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
  <script src="../bower_components/angular-toastr/dist/angular-toastr.tpls.js"></script>
  <script src="../bower_components/moment/moment.js"></script>
  <script src="../bower_components/angular-translate/angular-translate.js"></script>
  <script src="../bower_components/angular-sanitize/angular-sanitize.js"></script>
  <script src="../bower_components/videogular/videogular.js"></script>
  <script src="../bower_components/videogular-controls/vg-controls.js"></script>
  <script src="../bower_components/videogular-buffering/vg-buffering.js"></script>
  <script src="../bower_components/underscore/underscore.js"></script>
  <script src="../bower_components/angular-underscore-module/angular-underscore-module.js"></script>
  <script src="../bower_components/angular-input-masks/angular-input-masks-standalone.js"></script>
  <script src="../bower_components/d3/d3.js"></script>
  <script src="../bower_components/c3/c3.js"></script>
  <script src="../bower_components/fullcalendar/dist/fullcalendar.js"></script>
  <script src="app/shared/util/calendar.js"></script>
  <script src="../bower_components/re-tree/re-tree.js"></script>
  <script src="../bower_components/ng-device-detector/ng-device-detector.js"></script>
  <script src="../bower_components/ngstorage/ngStorage.js"></script>
  <script src="../bower_components/videogular-overlay-play/vg-overlay-play.js"></script>
  <script src="../bower_components/videogular-poster/vg-poster.js"></script>
  <script src="../bower_components/angular-xeditable/dist/js/xeditable.js"></script>
  <script src="../bower_components/SHA-1/sha1.js"></script>
  <script src="../bower_components/angulartics/src/angulartics.js"></script>
  <script src="../bower_components/angulartics-google-analytics/lib/angulartics-google-analytics.js"></script>
  <script src="../bower_components/moment-timezone/builds/moment-timezone-with-data-2010-2020.js"></script>
  <script src="../bower_components/spin.js/spin.js"></script>
  <script src="../bower_components/angular-spinner/angular-spinner.js"></script>
  <script src="../bower_components/highcharts/highcharts.js"></script>
  <script src="../bower_components/highcharts/highcharts-more.js"></script>
  <script src="../bower_components/highcharts/modules/exporting.js"></script>
  <script src="../bower_components/highcharts/modules/no-data-to-display.js"></script>
  <script src="../bower_components/seiyria-bootstrap-slider/dist/bootstrap-slider.js"></script>
  <script src="../bower_components/angular-bootstrap-slider/slider.js"></script>
  <script src="../bower_components/opentok-layout-js/opentok-layout.js"></script>
  <script src="../bower_components/opentok-angular/opentok-angular.js"></script>
  <script src="../bower_components/ng-idle/angular-idle.js"></script>
  <script src="../bower_components/angular-carousel/dist/angular-carousel.js"></script>
  <script src="../bower_components/angularjs-datepicker/dist/angular-datepicker.js"></script>
  <script src="../bower_components/angular-uuid/uuid.min.js"></script>
  <script src="../bower_components/waypoints/lib/noframework.waypoints.js"></script>
  <script src="../bower_components/angulartics-scroll/dist/angulartics-scroll.min.js"></script>
  <script src="../bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.js"></script>
  
  
  
  
  <script src="/app/index.module.js"></script>
  
  
  
  
  
</body>
</html>

I have also tried to with using the angular-translate-cookie and storelocale but no luck 

Can someone pls help to resolve it.

**Comment by jitugeo** [comment]
@knalli 
@mchambaud 
@PascalPrecht

**Comment by knalli** [comment]
Hi @jitugeo 

Please...

- report issues at our main repo as being described at the front page
- provide full working demos as being described in the issue template
- avoid blind mention other people, regardless if they are responsible for this actually

In short what I got so far: `Unknown provider: $translateStaticFilesLoaderProvider <- $translateStaticFilesLoader` means the requested component (static files loader) is not well known in your application. Maybe not loaded, mybe not included. I don't know, we don't know.
