### ISSUE TITLE
Where to put my language files?

### ISSUE THREAD

**Issue by manulitopetito** [angular-translate/bower-angular-translate-loader-static-files#8]
Hi!

First of all: Thanks for the great work!

I have one problem: When i export my language strings into a separate json file - where should I put it?
I tried the following:

    app/
    --js/
    ----i18n/
    ----------lang-de_DE.json
    ----app.js  // the implementation in the config file

    $translateProvider.useStaticFilesLoader({
      prefix: 'i18n/lang-',
      suffix: '.json'
    });

But unfortunately, it won't load. Could you help me out on this?

**Comment by tspaeth** [comment]
Could you please file issues in our main repository
https://github.com/angular-translate/angular-translate/issues

This is just the bower distribution repo. thanks.
