### ISSUE TITLE
Failing to load multiple files , using { 

### ISSUE THREAD

**Issue by aykutyararbas** [angular-translate/bower-angular-translate-loader-static-files#9]
$http(angular.extend({
        url: [
          file.prefix,
          file.key,
          file.suffix
        ].join(''),
        method: 'GET',
        params: ''
      }, options.$http)).success(function (data) {
        deferred.resolve(data);
      }).error(function (data) {
        deferred.reject(file.key);
      });

**Comment by tspaeth** [comment]
I guess, this is an error and #10 should be the right one? closing this.
Anyway: This is the wrong repo for filing issues. Please use our main repo.
